- name: Ensure chocolatey is installed
  win_chocolatey:
    name:
    - chocolatey
    - chocolatey-core.extension
    state: present

- name: Install multiple packages sequentially
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
  - git

- name: Windows | Check for OctopusDSC Powershell module
  win_psmodule:
    name: OctopusDSC
    state: present

- name: Windows | Configure local Octopus Server with DSC
  win_dsc:
    resource_name: cOctopusServer
    Ensure: "Present"
    State: "Started"
    Name: "OctopusServer"
    WebListenPrefix: "http://localhost:8080"
    SqlDbConnectionString: "Server=localhost;Database=Octopus;Trusted_Connection=True;"
    OctopusAdminCredential_username: Administrator@octopusadlab.local
    OctopusAdminCredential_password: StrongPass123!
    AllowUpgradeCheck: false
    AllowCollectionOfUsageStatistics: false
    AutoLoginEnabled: true

- name: Windows | Configure local Octopus Server AD auth with DSC
  win_dsc:
    resource_name: cOctopusServerActiveDirectoryAuthentication
    InstanceName: "OctopusServer"
    Enabled: true
