- name: Change the hostname to member-server
  win_hostname:
    name: member-server
  register: win_hostname

- name: Reboot if needed
  win_reboot:
  when: win_hostname.reboot_required

- name: Set configure dns
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - 192.168.56.10
    log_path: C:\dns_log.txt

- name: Add member server to octopusadlab.local
  win_domain_membership:
    dns_domain_name: octopusadlab.local
    domain_admin_user: Administrator@octopusadlab.local
    domain_admin_password: StrongPass123!
    state: domain
  register: domain_state

- name: Reboot if needed
  win_reboot:
  when: domain_state.reboot_required
